easy_admin:
  entities:
    - App\Entity\Admin
    - App\Entity\AdminHasReport
    - App\Entity\Bin
    - App\Entity\Consumer
    - App\Entity\ConsumerHasBin
    - App\Entity\Report
  user:
    name_property_path: 'login'
