security:
  providers:
    entity_provider:
      entity:
        class: 'App\Entity\Admin'
        property: 'login'
  encoders:
    App\Entity\Admin:
      algorithm: auto

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
      stateless: true
    login:
      pattern: ^/api/login
      stateless: true
      anonymous: true
      json_login:
        check_path:               /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    api:
      pattern:   ^/api
      stateless: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
      logout:
        path: 'logout'
    classic:
      anonymous: ~
      guard:
        authenticators:
          - App\Security\LoginAuthenticator



  access_control:
    - { path: ^/login, roles:  ROLE_ADMIN}
    - { path: ^/api/*, roles: IS_AUTHENTICATED_FULLY}
    - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: ^/admin/*, roles: [IS_AUTHENTICATED_FULLY, ROLE_ADMIN]}
    - { path: ^/reports/*, roles: [IS_AUTHENTICATED_FULLY, ROLE_ADMIN]}
    - { path: ^/bins/*, roles: [IS_AUTHENTICATED_FULLY, ROLE_ADMIN]}

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
